site_name: AuthCore Documentation
site_description: Централізований мікросервіс автентифікації та авторизації
site_author: AuthCore Team
site_url: https://AndriiLupoi.github.io/authcore-docs/

theme:
  name: material
  language: uk
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Темна тема
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Світла тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - swagger-ui-tag

nav:
  - Головна: README.md
  - Архітектура:
      - System Specification (SSD): architecture/SSD.md
      - Software Design (SDD): architecture/SDD.md
      - Infrastructure (ISD): architecture/ISD.md
  - Якість:
      - Test Strategy: quality/test-strategy.md
      - Traceability Matrix: quality/traceability-matrix.md
  - Розробникам:
      - Onboarding: developer/onboarding.md
  - API Documentation:
      - Опис API: api/index.md
      - OpenAPI Специфікація(завантажити): api/openapi.yaml
      - Інтерактивний Swagger UI: api/swagger.md
  - Візуальна документація UI: frontend/storybook.md
  - CI/CD автоматизація: ci-cd-docs.md
  - Definition of Done: definition-of-done.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist

extra_css:
  - https://unpkg.com/swagger-ui-dist@5/swagger-ui.css

extra_javascript:
  - https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js
  - https://unpkg.com/swagger-ui-dist@5/swagger-ui-standalone-preset.js